import java.io.Serializable;
import java.util.Date;

/**
 * 리뷰 댓글 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReviewSemiproject implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글 아이디. */
	private Integer rid;

	/** 사용자 테이블. */
	private UserSemiproject user;

	/** 동물 유치원 정보. */
	private BoardSemiproject board;

	/** 댓글 내용. */
	private String content;

	/** 내가 작성했는지 여부. */
	private Integer ismine;

	/** 평점. */
	private Integer grade;

	/** 작성일. */
	private Date modtime;

	/** 삭제 여부. */
	private Integer isdel;

	/**
	 * 생성자.
	 */
	public ReviewSemiproject() {
	}

	/**
	 * 댓글 아이디을 설정합니다..
	 * 
	 * @param rid
	 *            댓글 아이디
	 */
	public void setRid(Integer rid) {
		this.rid = rid;
	}

	/**
	 * 댓글 아이디을 가져옵니다..
	 * 
	 * @return 댓글 아이디
	 */
	public Integer getRid() {
		return this.rid;
	}

	/**
	 * 사용자 테이블을 설정합니다..
	 * 
	 * @param user
	 *            사용자 테이블
	 */
	public void setUser(UserSemiproject user) {
		this.user = user;
	}

	/**
	 * 사용자 테이블을 가져옵니다..
	 * 
	 * @return 사용자 테이블
	 */
	public UserSemiproject getUser() {
		return this.user;
	}

	/**
	 * 동물 유치원 정보을 설정합니다..
	 * 
	 * @param board
	 *            동물 유치원 정보
	 */
	public void setBoard(BoardSemiproject board) {
		this.board = board;
	}

	/**
	 * 동물 유치원 정보을 가져옵니다..
	 * 
	 * @return 동물 유치원 정보
	 */
	public BoardSemiproject getBoard() {
		return this.board;
	}

	/**
	 * 댓글 내용을 설정합니다..
	 * 
	 * @param content
	 *            댓글 내용
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * 댓글 내용을 가져옵니다..
	 * 
	 * @return 댓글 내용
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * 내가 작성했는지 여부을 설정합니다..
	 * 
	 * @param ismine
	 *            내가 작성했는지 여부
	 */
	public void setIsmine(Integer ismine) {
		this.ismine = ismine;
	}

	/**
	 * 내가 작성했는지 여부을 가져옵니다..
	 * 
	 * @return 내가 작성했는지 여부
	 */
	public Integer getIsmine() {
		return this.ismine;
	}

	/**
	 * 평점을 설정합니다..
	 * 
	 * @param grade
	 *            평점
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	/**
	 * 평점을 가져옵니다..
	 * 
	 * @return 평점
	 */
	public Integer getGrade() {
		return this.grade;
	}

	/**
	 * 작성일을 설정합니다..
	 * 
	 * @param modtime
	 *            작성일
	 */
	public void setModtime(Date modtime) {
		this.modtime = modtime;
	}

	/**
	 * 작성일을 가져옵니다..
	 * 
	 * @return 작성일
	 */
	public Date getModtime() {
		return this.modtime;
	}

	/**
	 * 삭제 여부을 설정합니다..
	 * 
	 * @param isdel
	 *            삭제 여부
	 */
	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

	/**
	 * 삭제 여부을 가져옵니다..
	 * 
	 * @return 삭제 여부
	 */
	public Integer getIsdel() {
		return this.isdel;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rid == null) ? 0 : rid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReviewSemiproject other = (ReviewSemiproject) obj;
		if (rid == null) {
			if (other.rid != null) {
				return false;
			}
		} else if (!rid.equals(other.rid)) {
			return false;
		}
		return true;
	}

}
